name: SDK Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-lint-and-test-sdk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/yarn-install-and-verify
        with: 
          cache_id: sdk
          working_dir: ./js
          skip_test: true
